<a href="https://colab.research.google.com/github/thanadolch/data_viz/blob/main/data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dictionary

In [1]:
ex_dict = {'a':10,'1':1,'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [2]:
ex_dict['a']

10

In [3]:
ex2_dict = {1:'one',2:'two',3:'three'}

In [4]:
print(ex2_dict[2])

two


###การเพิ่มสมาชิก

In [5]:
ex2_dict[0] = 'zero'

In [6]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

#คำสั่ง

In [7]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [8]:
for index in ex2_dict.keys():
    print(index)

1
2
3
0


In [9]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

dict เอาไปใช้ร่วมกับ Dataframe ของ pandas

# Numpy Array (array n มิติ)

In [10]:
import numpy as np #วิธีเรียกใช้ numpy

In [11]:
ex_2d_array = np.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


การชี้ค่าใน numpy array

In [12]:
ex_2d_array[1,1]

0.1

In [13]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]

In [14]:
list_x[0]
list_x[1][2]

0.3

## operations

In [15]:
ex2_2d_array = np.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)

[[1 0 0]
 [0 0 1]]


In [16]:
ex_2d_array.shape #ตรวจขนาดของ matrix

(2, 3)

In [17]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [18]:
ex_2d_array * ex2_2d_array #การคูณ Array

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [19]:
print(ex2_2d_array.T)

[[1 0]
 [0 0]
 [0 1]]


In [20]:
m = np.dot(ex_2d_array,ex2_2d_array.T)

In [21]:
np.linalg.det(m)

-39.389999999999986

### matrix slicing

In [22]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [23]:
ex_2d_array[1,1:]

array([0.1, 0.3])

HW 5 เขียน function คูณ matrix

แล้ว testbกับ matrix 

- (2,3)*(3,2)
- (4,4)*(4,1)
- (2,2)*(2,2)

Zeros,Ones,Randoms

In [24]:
np.zeros(2)

array([0., 0.])

In [26]:
np.zeros((2,1))

array([[0.],
       [0.]])

# Ones

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#Matrix Operation (Scalar multiplication)

In [28]:
one = np.ones((3,3))

one*2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [31]:
np.random.rand(3,2) #uniform random

array([[0.67650958, 0.68470592],
       [0.46847155, 0.26760561],
       [0.61045853, 0.30479397]])

In [32]:
np.random.randn(3,2) #normal distibution

array([[-0.78034769, -0.67548269],
       [-0.21542736,  0.30677391],
       [ 0.40429461, -0.54166231]])

In [40]:
np.random.choice([1,2,3,4,5],size=25,p = [0.1,0.2,0.4,0.2,0.1])

array([5, 2, 2, 3, 2, 4, 2, 3, 3, 3, 3, 3, 4, 4, 2, 5, 4, 3, 2, 1, 2, 3,
       3, 4, 5])

# เฉลย HW5

In [52]:
def mul_mat(A,B):
    c = np.zeros((A.shape[0],B.shape[1]))
    for r_a in range(A.shape[0]):
        for c_b in range(B.shape[1]):
            for every_element in range(A.shape[1]):
                c[r_a,c_b] = c[r_a,c_b]+(A[r_a,every_element]*B[every_element,c_b])
    return c

In [53]:
mat1 = np.array([[1,2,3],[5,6,9]])
mat2 = np.array([[9,8],[5,4],[7,5]])

In [54]:
mat1.shape[1]

3

In [55]:
mul_mat(mat1,mat2)

array([[ 40.,  31.],
       [138., 109.]])