<a href="https://colab.research.google.com/github/thanadolch/data_viz/blob/main/data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dictionary

In [1]:
ex_dict = {'a':10,'1':1,'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [4]:
ex_dict['a']

10

In [6]:
ex2_dict = {1:'one',2:'two',3:'three'}

In [8]:
print(ex2_dict[2])

two


###การเพิ่มสมาชิก

In [10]:
ex2_dict[0] = 'zero'

In [11]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

#คำสั่ง

In [12]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [13]:
for index in ex2_dict.keys():
    print(index)

1
2
3
0


In [14]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

dict เอาไปใช้ร่วมกับ Dataframe ของ pandas

# Numpy Array (array n มิติ)

In [17]:
import numpy as np #วิธีเรียกใช้ numpy

In [22]:
ex_2d_array = np.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


การชี้ค่าใน numpy array

In [24]:
ex_2d_array[1,1]

0.1

In [25]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]

In [29]:
list_x[0]
list_x[1][2]

0.3

## operations

In [31]:
ex2_2d_array = np.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)

[[1 0 0]
 [0 0 1]]


In [32]:
ex_2d_array.shape #ตรวจขนาดของ matrix

(2, 3)

In [33]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [35]:
ex_2d_array * ex2_2d_array #การคูณ Array

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [36]:
print(ex2_2d_array.T)

[[1 0]
 [0 0]
 [0 1]]


In [38]:
m = np.dot(ex_2d_array,ex2_2d_array.T)

In [39]:
np.linalg.det(m)

-39.389999999999986

### matrix slicing

In [40]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [41]:
ex_2d_array[1,1:]

array([0.1, 0.3])

HW 5 เขียน function คูณ matrix

แล้ว testbกับ matrix 

- (2,3)*(3,2)
- (4,4)*(4,1)
- (2,2)*(2,2)